apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-certificate
spec:
  secretName: blog-ssl-secret
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - blog.danieliu.xyz
