---
- name: copy ssh_config
  become: yes
  copy:
    dest: /etc/ssh/sshd_config
    src: etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
- name: reload sshd
  become: yes
  service:
    name: sshd
    state: reloaded 
